# -*- coding: utf-8 -*-
"""detect_mask_video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gm0uLb56AecDYOfhFDCDxtUinDFB1stm
"""

# import the necessary packages
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
from imutils.video import VideoStream
from imutils.video import FileVideoStream
from imutils.video import FPS
import numpy as np
import imutils
import time
import cv2
import os
import tkinter.filedialog

def detect_and_predict_mask(frame, faceNet, maskNet):
	# grab the dimensions of the frame and then construct a blob
	# from it
	(h, w) = frame.shape[:2]
	blob = cv2.dnn.blobFromImage(frame, 1.0, (224, 224),
		(104.0, 177.0, 123.0))

	# pass the blob through the network and obtain the face detections
	faceNet.setInput(blob)
	detections = faceNet.forward()
	print(detections.shape)

	# initialize our list of faces, their corresponding locations,
	# and the list of predictions from our face mask network
	faces = []
	locs = []
	preds = []

	# loop over the detections
	for i in range(0, detections.shape[2]):
		# extract the confidence (i.e., probability) associated with
		# the detection
		confidence = detections[0, 0, i, 2]

		# filter out weak detections by ensuring the confidence is
		# greater than the minimum confidence
		if confidence > 0.5:
			# compute the (x, y)-coordinates of the bounding box for
			# the object
			box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
			(startX, startY, endX, endY) = box.astype("int")

			# ensure the bounding boxes fall within the dimensions of
			# the frame
			(startX, startY) = (max(0, startX), max(0, startY))
			(endX, endY) = (min(w - 1, endX), min(h - 1, endY))

			# extract the face ROI, convert it from BGR to RGB channel
			# ordering, resize it to 224x224, and preprocess it
			face = frame[startY:endY, startX:endX]
			face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
			face = cv2.resize(face, (224, 224))
			face = img_to_array(face)
			face = preprocess_input(face)

			# add the face and bounding boxes to their respective
			# lists
			faces.append(face)
			locs.append((startX, startY, endX, endY))

	# only make a predictions if at least one face was detected
	if len(faces) > 0:
		# for faster inference we'll make batch predictions on *all*
		# faces at the same time rather than one-by-one predictions
		# in the above `for` loop
		faces = np.array(faces, dtype="float32")
		preds = maskNet.predict(faces, batch_size=32)

	# return a 2-tuple of the face locations and their corresponding
	# locations
	return (locs, preds)

# load our serialized face detector model from disk
prototxtPath = r"face_detector\deploy.prototxt"
weightsPath = r"face_detector\res10_300x300_ssd_iter_140000.caffemodel"
faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)

# load the face mask detector model from disk
mask_detector_model = r"mask_detector.model"
maskNet = load_model(mask_detector_model)

# Ask whether the user wants to use a live webcam
# or open an existing video

userOptions = ['webcam', 'video']
while True:
	userChoice = input('Would you like to use the webcam or open an existing video? Type "webcam" or "video". ').lower()
	if userChoice in userOptions:
		break
	else:
		print('Please, type "webcam" or "video"')

if userChoice == 'video':
	# Ask the user for the file
	print('Please, pick the file.')
	videoDirectory = tkinter.filedialog.askopenfilename()
	vs = FileVideoStream(videoDirectory).start()
else:
	# initialize the video stream
	print("[INFO] Starting video stream...")
	vs = VideoStream(src=0, resolution=(1280, 720)).start()


# Ask whether the user wants to save the output video
userSaveChoiceOptions = ['Y', 'N']
while True:
	userSaveChoice = input('Would you like to save the output video? (Y/N) ')
	if userSaveChoice in ['Yes', 'yes', 'y', 'YES']:
		userSaveChoice = 'Y'
	elif userSaveChoice in ['No', 'no', 'n', 'NO']:
		userSaveChoice = 'N'
	if userSaveChoice.upper() in userSaveChoiceOptions:
		break
	else:
		print('Please, type "Y" or "N".')

# Ask where the user wants to save the video
# and with what name
if userSaveChoice == 'Y':
	print('Where would you like to save the output video?')
	saveDirectory = tkinter.filedialog.askdirectory()
	print(saveDirectory)
	saveName = input('What would you like to name the output video? ')
	joiner = (saveDirectory, '/', saveName, '.avi')
	# Output directory
	saveOutputDirectory = ''.join(joiner)

totalVideoTime = 0
maskWearing = 0
listFrames = []
fps = FPS().start()

# loop over the frames from the video stream / video
while True:
	# grab the frame from the threaded video stream
	frame = vs.read()

	# Stop the loop if the user used a video file and the video finished
	if frame is None:
		break

	# Resize the frame
	frame = imutils.resize(frame, width=1000)

	# detect faces in the frame and determine if they are wearing a
	# face mask or not
	(locs, preds) = detect_and_predict_mask(frame, faceNet, maskNet)

	# loop over the detected face locations and their corresponding
	# locations
	for (box, pred) in zip(locs, preds):
		# unpack the bounding box and predictions
		(startX, startY, endX, endY) = box
		(mask, withoutMask) = pred

		totalVideoTime += 1
		if mask > withoutMask:
			maskWearing += 1

		# determine the class label and color we'll use to draw
		# the bounding box and text
		label = "Mask" if mask > withoutMask else "No Mask"
		color = (0, 255, 0) if label == "Mask" else (0, 0, 255)

		# include the probability in the label
		label = "{}: {:.2f}%".format(label, max(mask, withoutMask) * 100)

		# display the label and bounding box rectangle on the output
		# frame
		cv2.putText(frame, label, (startX, startY - 10),
			cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
		cv2.rectangle(frame, (startX, startY), (endX, endY), color, 2)

	listFrames.append(frame)

	# Telling the user how to stop the webcam interface
	if userChoice == 'webcam':
		cv2.putText(frame, 'Press "Q" to stop the webcam', (50,50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,100,0), 2)

	# show the output frame
	cv2.imshow("Detecting Face Mask...", frame)
	key = cv2.waitKey(1) & 0xFF
	fps.update()

	# if the `q` key was pressed, break from the loop
	if key == ord("q"):
		break

fps.stop()

# Save video
if userSaveChoice == 'Y':
	size = listFrames[1].shape[1], listFrames[1].shape[0]
	output = cv2.VideoWriter(saveOutputDirectory, cv2.VideoWriter_fourcc('M','J','P','G'), fps.fps(), size)
	for i in listFrames:
		output.write(i)
	output.release()

cv2.destroyAllWindows()
vs.stop()

# Show user how long the mask was worn (only works with one person)
print('The mask was probably worn', maskWearing/totalVideoTime * 100, '% of the time.')
